(define (is_eq a b) 
    (= a b)
)

(define (sum_of_squares a b)
    (+ (* a a) (* b b))
)

(define (biggest_squares a b c)
    (if (> a b)
        (if (> b c)
            (sum_of_squares a b)
            (sum_of_squares a c)
        )
        (if (> a c)
            (sum_of_squares b a)
            (sum_of_squares b c)
        )
    )
)

(is_eq (biggest_squares 1 2 3) 13)
(is_eq (biggest_squares 4 2 3) 25)
(is_eq (biggest_squares 0 0 0) 0)
(is_eq (biggest_squares 1 0 1) 2)
(is_eq (biggest_squares 2 3 2) 13)
