(define (biggest_squares a b c)
  (cond ( (or (and (<= a b) (<= a c) (+ (* b b) (* c c)))
              (and (<= b a) (<= b c) (+ (* a a) (* c c)))
              (and (<= c a) (<= c b) (+ (* a a) (* b b)))))))

(biggest_squares 1 2 3)
(biggest_squares 4 2 3)
(biggest_squares 0 0 0)
(biggest_squares 1 0 1)
(biggest_squares 2 3 2)
